:stats: {
        :cells_read: { :pair: [:cells_read, :cells_written],
                       :units: "" ,
                       :color: ["#edd400", "#73d216"],
                       :pname: "Cells Read"},
        :cells_written: {
                       :pair: [:cells_read, :cells_written],
                       :units: "" ,
                       :color: ["#edd400", "#73d216"],
                       :pname: "Cells Written",
                       :flag: "1"
                      },

        :mem_used: {
                      :pair: [:mem_used],
                      :units: "Bytes",
                      :color: '["#c17d11"]',
                      :pname: "Memory Used"
                      },

        :percent_mem_used: {
                     :pair: [:mem_used, :mem_total],
                     :units: "%",
                     :pname: "Percent Mem Used",
                     :color: ["#cc0000", "#73d216"]
                     },
        :percent_query_cache_memory_used: {
                     :pair: [:q_c_avail_mem, :q_c_max_mem],
                     :units: "%",
                     :pname: "Percent Query Cache Memory Used" ,
                     :color: ["#8ae234", "#ef2929"]},

        :net_recv_KBps: {
                     :pair: [:net_recv_KBps, :net_sent_KBps],
                     :color: ["#c17d11", "#888a85"] ,
                     :units: "KBps",
                     :pname: "Net Recv KBps"},

        :net_sent_KBps: {
                     :pair: [:net_recv_KBps, :net_sent_KBps],
                     :color: ["#c17d11", "#888a85"] ,
                     :units: "KBps",
                     :pname: "Net Send KBps"},

        :bytes_read: {
                     :pair: [:bytes_read, :bytes_written],
                     :color: ["#c17d11", "#888a85"],
                     :units: "Bytes",
                     :pname: "Bytes Read"},

        :bytes_written: {
                     :pair: [:bytes_read, :bytes_written],
                     :color: ["#c17d11", "#888a85"],
                     :units: "Bytes",
                     :pname: "Bytes Written"},

        :q_c_accesses: {
                     :pair: [:q_c_accesses, :q_c_hits],
                     :color: ["#8ae234", "#ef2929"],
                     :units: "",
                     :pname: "Query Cache Accesses"},
        :q_c_hits: {
                     :pair: [:q_c_accesses, :q_c_hits],
                     :color: ["#8ae234", "#ef2929"],
                     :units: "",
                     :pname: "Query Cache Hits"},

        :loadavg: {
                    :pair: [:loadavg],
                    :color: ["#73d216"],
                    :units: "",
                    :pname: "Load Avg"},

       :mem_used: {
                  :pair: [:mem_used],
                  :color: ["#fcaf3e"],
                  :units: "KB" ,
                  :pname: "Mem Used"},

        :q_c_avail_mem: {
                  :pair: [:q_c_avail_mem],
                  :color: ["#fcaf3e"],
                  :units: "KB" ,
                  :pname: "Query Cache Available Memory"},

        :q_c_max_mem: {
                  :pair: [:q_c_max_mem],
                  :color: ["#ef2929"],
                  :units: "KB" ,
                  :pname: "Query Cache Max Memory"},

        :mem_total: {
                  :pair: [:mem_total],
                  :units: "Bytes",
                  :color: ["#5c3566"],
                  :pname: "Mem Total"},
        :clock_mhz: {
                  :pair: [:clock_mhz],
                  :units: "",
                  :color: ["#edd400"],
                  :pname: "Clock Mhz"},

        :num_cores: {
                  :pair: [:num_cores],
                  :units: "",
                  :color: ["#73d216"],
                  :pname: "Num Cores"},
        :num_ranges: {
                   :pair: [:num_ranges],
                   :units: "",
                   :color: ["#3465a4"],
                   :pname: "Num Ranges"},

         :scans: {
                   :pair: [:scans],
                   :units: "",
                   :color: ["#cc0000"],
                   :pname: "Scans"},
         :syncs: {
                   :pair: [:syncs],
                   :units: "",
                   :color: ["#cc0000"],
                   :pname: "Syncs"},

         :b_c_accesses: {
                    :pair: [:b_c_accesses, :b_c_hits],
                    :color: ["#cc0000", "#5c3566"],
                    :units: "",
                    :pname: "Block Cache Access"},
         :b_c_hits: {
                    :pair: [:b_c_accesses, :b_c_hits],
                    :color: ["#cc0000", "#5c3566"],
                    :units: "",
                    :pname: "Block Cache Hits",
                    :flag: "1"  },

        :vm_size: {
                  :pair: [:vm_size],
                  :color: ["#ef2929"],
                  :units: "KB",
                  :pname: "Virtual Machine Size"},

        :vm_resident: {
                  :pair: [:vm_resident],
                  :color: ["#73d216"],
                  :units: "KB",
                  :pname: "Virtual Machine Resident"},

        :cpu_pct: {
                  :pair: [:cpu_pct],
                  :color: ["#cc0000"],
                  :units: "percent",
                  :pname: "Cpu Percent"},

        :b_c_max_mem: {
                  :pair: [:b_c_max_mem],
                  :color: ["#cc0000"],
                  :units: "Bytes",
                  :pname: "Block Cache Max Memory"}

}
