:stats: {
        :cells_read: { :pair: [:cells_read],
                       :units: "" ,
                       :color: ["#edd400"],
                       :pname: "Cells Read"},
        :cells_written: {
                       :pair: [:cells_written],
                       :units: "" ,
                       :color: ["#73d216"],
                       :pname: "Cells Written",
                       :flag: "1"
                      },

        :mem_used: {
                      :pair: [:mem_used],
                      :units: "Bytes",
                      :color: '["#c17d11"]',
                      :pname: "Memory Used"
                      },

        :net_recv_KBps: {
                     :pair: [:net_recv_KBps],
                     :color: ["#c17d11"] ,
                     :units: "KBps",
                     :pname: "Net Recv KBps"},

        :net_sent_KBps: {
                     :pair: [:net_sent_KBps],
                     :color: ["#888a85"] ,
                     :units: "KBps",
                     :pname: "Net Send KBps"},

        :bytes_read: {
                     :pair: [:bytes_read],
                     :color: ["#c17d11"],
                     :units: "Bytes",
                     :pname: "Bytes Read"},

        :bytes_written: {
                     :pair: [:bytes_written],
                     :color: [ "#888a85"],
                     :units: "Bytes",
                     :pname: "Bytes Written"},

        :q_c_accesses: {
                     :pair: [:q_c_accesses],
                     :color: ["#8ae234"],
                     :units: "",
                     :pname: "Query Cache Accesses"},
        :q_c_hits: {
                     :pair: [:q_c_hits],
                     :color: ["#ef2929"],
                     :units: "",
                     :pname: "Query Cache Hits"},

        :loadavg: {
                    :pair: [:loadavg],
                    :color: ["#73d216"],
                    :units: "",
                    :pname: "Load Avg"},

       :mem_used: {
                  :pair: [:mem_used],
                  :color: ["#fcaf3e"],
                  :units: "KB" ,
                  :pname: "Mem Used"},

        :q_c_avail_mem: {
                  :pair: [:q_c_avail_mem],
                  :color: ["#fcaf3e"],
                  :units: "KB" ,
                  :pname: "Query Cache Available Memory"},


         :scans: {
                   :pair: [:scans],
                   :units: "",
                   :color: ["#cc0000"],
                   :pname: "Scans"},
         :syncs: {
                   :pair: [:syncs],
                   :units: "",
                   :color: ["#cc0000"],
                   :pname: "Syncs"},

         :b_c_accesses: {
                    :pair: [:b_c_accesses],
                    :color: ["#cc0000"],
                    :units: "",
                    :pname: "Block Cache Access"},
         :b_c_hits: {
                    :pair: [:b_c_hits],
                    :color: ["#5c3566"],
                    :units: "",
                    :pname: "Block Cache Hits",
                    :flag: "1"  },

        :vm_size: {
                  :pair: [:vm_size],
                  :color: ["#ef2929"],
                  :units: "KB",
                  :pname: "Virtual Memory Size"},

        :vm_resident: {
                  :pair: [:vm_resident],
                  :color: ["#73d216"],
                  :units: "KB",
                  :pname: "Virtual Memory Resident"},

        :cpu_pct: {
                  :pair: [:cpu_pct],
                  :color: ["#cc0000"],
                  :units: "percent",
                  :pname: "Cpu Percent"}

}
